default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials[Rails.env.to_sym][:psql][:user] %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:psql][:password] %>
  pool: 5
  timeout: 5000
  host: <%= Rails.application.credentials[Rails.env.to_sym][:psql][:host] %>

development:
  <<: *default
  database: <%= Rails.application.credentials[Rails.env.to_sym][:psql][:dbname] %>

test:
  <<: *default
  database: <%= Rails.application.credentials[Rails.env.to_sym][:psql][:dbname] %>

production:
  <<: *default
  database: <%= Rails.application.credentials[Rails.env.to_sym][:psql][:dbname] %>